// Code generated by "enumer -type=Permit -text"; DO NOT EDIT.

//
package enums

import (
	"fmt"
)

const (
	_PermitName_0 = "NoopBatchView"
	_PermitName_1 = "Draft"
	_PermitName_2 = "Delete"
	_PermitName_3 = "Add"
	_PermitName_4 = "Edit"
	_PermitName_5 = "Export"
)

var (
	_PermitIndex_0 = [...]uint8{0, 4, 9, 13}
	_PermitIndex_1 = [...]uint8{0, 5}
	_PermitIndex_2 = [...]uint8{0, 6}
	_PermitIndex_3 = [...]uint8{0, 3}
	_PermitIndex_4 = [...]uint8{0, 4}
	_PermitIndex_5 = [...]uint8{0, 6}
)

func (i Permit) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _PermitName_0[_PermitIndex_0[i]:_PermitIndex_0[i+1]]
	case i == 4:
		return _PermitName_1
	case i == 8:
		return _PermitName_2
	case i == 16:
		return _PermitName_3
	case i == 32:
		return _PermitName_4
	case i == 64:
		return _PermitName_5
	default:
		return fmt.Sprintf("Permit(%d)", i)
	}
}

var _PermitValues = []Permit{0, 1, 2, 4, 8, 16, 32, 64}

var _PermitNameToValueMap = map[string]Permit{
	_PermitName_0[0:4]:  0,
	_PermitName_0[4:9]:  1,
	_PermitName_0[9:13]: 2,
	_PermitName_1[0:5]:  4,
	_PermitName_2[0:6]:  8,
	_PermitName_3[0:3]:  16,
	_PermitName_4[0:4]:  32,
	_PermitName_5[0:6]:  64,
}

// PermitString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PermitString(s string) (Permit, error) {
	if val, ok := _PermitNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Permit values", s)
}

// PermitValues returns all values of the enum
func PermitValues() []Permit {
	return _PermitValues
}

// IsAPermit returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Permit) IsAPermit() bool {
	for _, v := range _PermitValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Permit
func (i Permit) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Permit
func (i *Permit) UnmarshalText(text []byte) error {
	var err error
	*i, err = PermitString(string(text))
	return err
}
